#!/usr/bin/env bash

git clone --recursive git@github.com:changs/slimzsh.git ~/.slimzsh

if [ -f ~/.zshrc ]; then
	cp ~/.zshrc ~/.zshrc_backup    
fi;

echo 'source "$HOME/.slimzsh/slim.zsh"' >> ~/.zshrc

echo "It's almost done! If you have not used zsh earlier then you need to set default shell to ZSH by running chsh -s /bin/zsh"