#!/usr/bin/env bash

git clone --recursive git@github.com:changs/slimzsh.git ~/.slimzsh

if [ -f ~/.zshrc ]; then
	cp ~/.zshrc ~/.zshrc_backup    
fi;

echo 'source "$HOME/.slimzsh/slim.zsh"' >> ~/.zshrc